baseURL = 'http://msattova.netlify.app/'
languageCode = 'ja'
title = 'msattova logs'
theme = "hugo-book"

author = 'msattova'

[taxonomies]
tag = "tags"
archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps=true
